// Global verfügbar: window.PLAYERS
const PLAYERS = [
  {name:"Julian Brandt", country:"Deutschland", position:"Mittelfeld", club:"Borussia Dortmund", aliases:["Brandt","Jule"]},
  {name:"Nico Schlotterbeck", country:"Deutschland", position:"Innenverteidiger", club:"Borussia Dortmund", aliases:["Schlotterbeck","Nico S."]},
  {name:"Gregor Kobel", country:"Schweiz", position:"Torwart", club:"Borussia Dortmund", aliases:["Kobel"]},
  {name:"Kai Havertz", country:"Deutschland", position:"Mittelfeld", club:"Arsenal", aliases:["Havertz"]},
  {name:"Erling Haaland", country:"Norwegen", position:"Stürmer", club:"Manchester City", aliases:["Haaland"]},
  {name:"Kylian Mbappé", country:"Frankreich", position:"Stürmer", club:"Real Madrid", aliases:["Mbappe","Mbappé"]},
  {name:"Jude Bellingham", country:"England", position:"Mittelfeld", club:"Real Madrid", aliases:["Bellingham"]},
  {name:"Robert Lewandowski", country:"Polen", position:"Stürmer", club:"Barcelona", aliases:["Lewandowski","Lewy"]},
  {name:"Jamal Musiala", country:"Deutschland", position:"Mittelfeld", club:"Bayern München", aliases:["Musiala"]},
  {name:"Kevin De Bruyne", country:"Belgien", position:"Mittelfeld", club:"Manchester City", aliases:["De Bruyne","KDB"]},
  {name:"Mohamed Salah", country:"Ägypten", position:"Stürmer", club:"Liverpool", aliases:["Salah","Mo Salah"]},
  {name:"Lionel Messi", country:"Argentinien", position:"Stürmer", club:"Inter Miami", aliases:["Messi","Leo Messi"]},
  {name:"Cristiano Ronaldo", country:"Portugal", position:"Stürmer", club:"Al Nassr", aliases:["Ronaldo","CR7"]},
  {name:"Gianluigi Donnarumma", country:"Italien", position:"Torwart", club:"Paris Saint-Germain", aliases:["Donnarumma"]},
  {name:"Rafael Leão", country:"Portugal", position:"Stürmer", club:"AC Milan", aliases:["Leao","Leão"]},
  {name:"Virgil van Dijk", country:"Niederlande", position:"Innenverteidiger", club:"Liverpool", aliases:["Van Dijk","VvD"]},
  {name:"Antoine Griezmann", country:"Frankreich", position:"Stürmer", club:"Atlético Madrid", aliases:["Griezmann"]},
  {name:"Luka Modrić", country:"Kroatien", position:"Mittelfeld", club:"Real Madrid", aliases:["Modric","Modrić"]},
  {name:"Pedri", country:"Spanien", position:"Mittelfeld", club:"Barcelona", aliases:["Pedri"]},
  {name:"Bukayo Saka", country:"England", position:"Flügel", club:"Arsenal", aliases:["Saka"]},
  {name:"Alphonso Davies", country:"Kanada", position:"Außenverteidiger", club:"Bayern München", aliases:["Davies","Phonzy"]},
  {name:"Marc-André ter Stegen", country:"Deutschland", position:"Torwart", club:"Barcelona", aliases:["Ter Stegen","ter Stegen","Stegen"]},
  {name:"Manuel Neuer", country:"Deutschland", position:"Torwart", club:"Bayern München", aliases:["Neuer"]},
  {name:"Harry Kane", country:"England", position:"Stürmer", club:"Bayern München", aliases:["Kane"]},
];
